package com.cy.eide.system.organization.entity;

import org.springframework.stereotype.Component;

import java.util.Date;

@Component
public class SysUser {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.CALENDAR
     *
     * @mbggenerated
     */
    private String calendar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LEVELS
     *
     * @mbggenerated
     */
    private Integer levels;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.SUPERIOR
     *
     * @mbggenerated
     */
    private String superior;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.DEFAULTAPPLICATION
     *
     * @mbggenerated
     */
    private String defaultapplication;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LOGINNO
     *
     * @mbggenerated
     */
    private String loginno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LOGINPWD
     *
     * @mbggenerated
     */
    private String loginpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.TELEPHONE
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.DOMAINID
     *
     * @mbggenerated
     */
    private String domainid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PROXYUSER
     *
     * @mbggenerated
     */
    private String proxyuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.FIELD1
     *
     * @mbggenerated
     */
    private String field1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.FIELD2
     *
     * @mbggenerated
     */
    private String field2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.FIELD3
     *
     * @mbggenerated
     */
    private String field3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.FIELD4
     *
     * @mbggenerated
     */
    private String field4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.FIELD5
     *
     * @mbggenerated
     */
    private String field5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.FIELD6
     *
     * @mbggenerated
     */
    private String field6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.FIELD7
     *
     * @mbggenerated
     */
    private String field7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.FIELD8
     *
     * @mbggenerated
     */
    private String field8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.FIELD9
     *
     * @mbggenerated
     */
    private String field9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.FIELD10
     *
     * @mbggenerated
     */
    private String field10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.DEFAULTDEPARTMENT
     *
     * @mbggenerated
     */
    private String defaultdepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ISDOMAINUSER
     *
     * @mbggenerated
     */
    private String isdomainuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.STARTPROXYTIME
     *
     * @mbggenerated
     */
    private Date startproxytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ENDPROXYTIME
     *
     * @mbggenerated
     */
    private Date endproxytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.USEIM
     *
     * @mbggenerated
     */
    private Boolean useim;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ORDERBYNO
     *
     * @mbggenerated
     */
    private Integer orderbyno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LASTMODIFYPASSWORDTIME
     *
     * @mbggenerated
     */
    private Date lastmodifypasswordtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PASSWORDARRAY
     *
     * @mbggenerated
     */
    private String passwordarray;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LOCKFLAG
     *
     * @mbggenerated
     */
    private Integer lockflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LASTNOTICETIME
     *
     * @mbggenerated
     */
    private Date lastnoticetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PUBLICKEY
     *
     * @mbggenerated
     */
    private String publickey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.DIMISSION
     *
     * @mbggenerated
     */
    private Integer dimission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PERMISSION_TYPE
     *
     * @mbggenerated
     */
    private String permissionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.LIAISON_OFFICER
     *
     * @mbggenerated
     */
    private Boolean liaisonOfficer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.TELEPHONE2
     *
     * @mbggenerated
     */
    private String telephone2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.TELEPHONEPUBLIC
     *
     * @mbggenerated
     */
    private Boolean telephonepublic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.TELEPHONEPUBLIC2
     *
     * @mbggenerated
     */
    private Boolean telephonepublic2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.EMAILPUBLIC
     *
     * @mbggenerated
     */
    private Boolean emailpublic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.USERINFOPUBLIC
     *
     * @mbggenerated
     */
    private Boolean userinfopublic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.NAME_LETTER
     *
     * @mbggenerated
     */
    private String nameLetter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.message_target
     *
     * @mbggenerated
     */
    private Integer messageTarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.AVATAR
     *
     * @mbggenerated
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.FAVORITE_CONTACTS
     *
     * @mbggenerated
     */
    private String favoriteContacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.SIGNS
     *
     * @mbggenerated
     */
    private String signs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.COMMONWORKFLOW
     *
     * @mbggenerated
     */
    private String commonworkflow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.ID
     *
     * @return the value of t_user.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.ID
     *
     * @param id the value for t_user.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.CALENDAR
     *
     * @return the value of t_user.CALENDAR
     *
     * @mbggenerated
     */
    public String getCalendar() {
        return calendar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.CALENDAR
     *
     * @param calendar the value for t_user.CALENDAR
     *
     * @mbggenerated
     */
    public void setCalendar(String calendar) {
        this.calendar = calendar == null ? null : calendar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.LEVELS
     *
     * @return the value of t_user.LEVELS
     *
     * @mbggenerated
     */
    public Integer getLevels() {
        return levels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.LEVELS
     *
     * @param levels the value for t_user.LEVELS
     *
     * @mbggenerated
     */
    public void setLevels(Integer levels) {
        this.levels = levels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.SUPERIOR
     *
     * @return the value of t_user.SUPERIOR
     *
     * @mbggenerated
     */
    public String getSuperior() {
        return superior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.SUPERIOR
     *
     * @param superior the value for t_user.SUPERIOR
     *
     * @mbggenerated
     */
    public void setSuperior(String superior) {
        this.superior = superior == null ? null : superior.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.DEFAULTAPPLICATION
     *
     * @return the value of t_user.DEFAULTAPPLICATION
     *
     * @mbggenerated
     */
    public String getDefaultapplication() {
        return defaultapplication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.DEFAULTAPPLICATION
     *
     * @param defaultapplication the value for t_user.DEFAULTAPPLICATION
     *
     * @mbggenerated
     */
    public void setDefaultapplication(String defaultapplication) {
        this.defaultapplication = defaultapplication == null ? null : defaultapplication.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.EMAIL
     *
     * @return the value of t_user.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.EMAIL
     *
     * @param email the value for t_user.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.LOGINNO
     *
     * @return the value of t_user.LOGINNO
     *
     * @mbggenerated
     */
    public String getLoginno() {
        return loginno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.LOGINNO
     *
     * @param loginno the value for t_user.LOGINNO
     *
     * @mbggenerated
     */
    public void setLoginno(String loginno) {
        this.loginno = loginno == null ? null : loginno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.LOGINPWD
     *
     * @return the value of t_user.LOGINPWD
     *
     * @mbggenerated
     */
    public String getLoginpwd() {
        return loginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.LOGINPWD
     *
     * @param loginpwd the value for t_user.LOGINPWD
     *
     * @mbggenerated
     */
    public void setLoginpwd(String loginpwd) {
        this.loginpwd = loginpwd == null ? null : loginpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.NAME
     *
     * @return the value of t_user.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.NAME
     *
     * @param name the value for t_user.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.TELEPHONE
     *
     * @return the value of t_user.TELEPHONE
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.TELEPHONE
     *
     * @param telephone the value for t_user.TELEPHONE
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.STATUS
     *
     * @return the value of t_user.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.STATUS
     *
     * @param status the value for t_user.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.DOMAINID
     *
     * @return the value of t_user.DOMAINID
     *
     * @mbggenerated
     */
    public String getDomainid() {
        return domainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.DOMAINID
     *
     * @param domainid the value for t_user.DOMAINID
     *
     * @mbggenerated
     */
    public void setDomainid(String domainid) {
        this.domainid = domainid == null ? null : domainid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.PROXYUSER
     *
     * @return the value of t_user.PROXYUSER
     *
     * @mbggenerated
     */
    public String getProxyuser() {
        return proxyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.PROXYUSER
     *
     * @param proxyuser the value for t_user.PROXYUSER
     *
     * @mbggenerated
     */
    public void setProxyuser(String proxyuser) {
        this.proxyuser = proxyuser == null ? null : proxyuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.remarks
     *
     * @return the value of t_user.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.remarks
     *
     * @param remarks the value for t_user.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.FIELD1
     *
     * @return the value of t_user.FIELD1
     *
     * @mbggenerated
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.FIELD1
     *
     * @param field1 the value for t_user.FIELD1
     *
     * @mbggenerated
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.FIELD2
     *
     * @return the value of t_user.FIELD2
     *
     * @mbggenerated
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.FIELD2
     *
     * @param field2 the value for t_user.FIELD2
     *
     * @mbggenerated
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.FIELD3
     *
     * @return the value of t_user.FIELD3
     *
     * @mbggenerated
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.FIELD3
     *
     * @param field3 the value for t_user.FIELD3
     *
     * @mbggenerated
     */
    public void setField3(String field3) {
        this.field3 = field3 == null ? null : field3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.FIELD4
     *
     * @return the value of t_user.FIELD4
     *
     * @mbggenerated
     */
    public String getField4() {
        return field4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.FIELD4
     *
     * @param field4 the value for t_user.FIELD4
     *
     * @mbggenerated
     */
    public void setField4(String field4) {
        this.field4 = field4 == null ? null : field4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.FIELD5
     *
     * @return the value of t_user.FIELD5
     *
     * @mbggenerated
     */
    public String getField5() {
        return field5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.FIELD5
     *
     * @param field5 the value for t_user.FIELD5
     *
     * @mbggenerated
     */
    public void setField5(String field5) {
        this.field5 = field5 == null ? null : field5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.FIELD6
     *
     * @return the value of t_user.FIELD6
     *
     * @mbggenerated
     */
    public String getField6() {
        return field6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.FIELD6
     *
     * @param field6 the value for t_user.FIELD6
     *
     * @mbggenerated
     */
    public void setField6(String field6) {
        this.field6 = field6 == null ? null : field6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.FIELD7
     *
     * @return the value of t_user.FIELD7
     *
     * @mbggenerated
     */
    public String getField7() {
        return field7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.FIELD7
     *
     * @param field7 the value for t_user.FIELD7
     *
     * @mbggenerated
     */
    public void setField7(String field7) {
        this.field7 = field7 == null ? null : field7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.FIELD8
     *
     * @return the value of t_user.FIELD8
     *
     * @mbggenerated
     */
    public String getField8() {
        return field8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.FIELD8
     *
     * @param field8 the value for t_user.FIELD8
     *
     * @mbggenerated
     */
    public void setField8(String field8) {
        this.field8 = field8 == null ? null : field8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.FIELD9
     *
     * @return the value of t_user.FIELD9
     *
     * @mbggenerated
     */
    public String getField9() {
        return field9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.FIELD9
     *
     * @param field9 the value for t_user.FIELD9
     *
     * @mbggenerated
     */
    public void setField9(String field9) {
        this.field9 = field9 == null ? null : field9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.FIELD10
     *
     * @return the value of t_user.FIELD10
     *
     * @mbggenerated
     */
    public String getField10() {
        return field10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.FIELD10
     *
     * @param field10 the value for t_user.FIELD10
     *
     * @mbggenerated
     */
    public void setField10(String field10) {
        this.field10 = field10 == null ? null : field10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.DEFAULTDEPARTMENT
     *
     * @return the value of t_user.DEFAULTDEPARTMENT
     *
     * @mbggenerated
     */
    public String getDefaultdepartment() {
        return defaultdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.DEFAULTDEPARTMENT
     *
     * @param defaultdepartment the value for t_user.DEFAULTDEPARTMENT
     *
     * @mbggenerated
     */
    public void setDefaultdepartment(String defaultdepartment) {
        this.defaultdepartment = defaultdepartment == null ? null : defaultdepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.ISDOMAINUSER
     *
     * @return the value of t_user.ISDOMAINUSER
     *
     * @mbggenerated
     */
    public String getIsdomainuser() {
        return isdomainuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.ISDOMAINUSER
     *
     * @param isdomainuser the value for t_user.ISDOMAINUSER
     *
     * @mbggenerated
     */
    public void setIsdomainuser(String isdomainuser) {
        this.isdomainuser = isdomainuser == null ? null : isdomainuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.STARTPROXYTIME
     *
     * @return the value of t_user.STARTPROXYTIME
     *
     * @mbggenerated
     */
    public Date getStartproxytime() {
        return startproxytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.STARTPROXYTIME
     *
     * @param startproxytime the value for t_user.STARTPROXYTIME
     *
     * @mbggenerated
     */
    public void setStartproxytime(Date startproxytime) {
        this.startproxytime = startproxytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.ENDPROXYTIME
     *
     * @return the value of t_user.ENDPROXYTIME
     *
     * @mbggenerated
     */
    public Date getEndproxytime() {
        return endproxytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.ENDPROXYTIME
     *
     * @param endproxytime the value for t_user.ENDPROXYTIME
     *
     * @mbggenerated
     */
    public void setEndproxytime(Date endproxytime) {
        this.endproxytime = endproxytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.USEIM
     *
     * @return the value of t_user.USEIM
     *
     * @mbggenerated
     */
    public Boolean getUseim() {
        return useim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.USEIM
     *
     * @param useim the value for t_user.USEIM
     *
     * @mbggenerated
     */
    public void setUseim(Boolean useim) {
        this.useim = useim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.ORDERBYNO
     *
     * @return the value of t_user.ORDERBYNO
     *
     * @mbggenerated
     */
    public Integer getOrderbyno() {
        return orderbyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.ORDERBYNO
     *
     * @param orderbyno the value for t_user.ORDERBYNO
     *
     * @mbggenerated
     */
    public void setOrderbyno(Integer orderbyno) {
        this.orderbyno = orderbyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.LASTMODIFYPASSWORDTIME
     *
     * @return the value of t_user.LASTMODIFYPASSWORDTIME
     *
     * @mbggenerated
     */
    public Date getLastmodifypasswordtime() {
        return lastmodifypasswordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.LASTMODIFYPASSWORDTIME
     *
     * @param lastmodifypasswordtime the value for t_user.LASTMODIFYPASSWORDTIME
     *
     * @mbggenerated
     */
    public void setLastmodifypasswordtime(Date lastmodifypasswordtime) {
        this.lastmodifypasswordtime = lastmodifypasswordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.PASSWORDARRAY
     *
     * @return the value of t_user.PASSWORDARRAY
     *
     * @mbggenerated
     */
    public String getPasswordarray() {
        return passwordarray;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.PASSWORDARRAY
     *
     * @param passwordarray the value for t_user.PASSWORDARRAY
     *
     * @mbggenerated
     */
    public void setPasswordarray(String passwordarray) {
        this.passwordarray = passwordarray == null ? null : passwordarray.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.LOCKFLAG
     *
     * @return the value of t_user.LOCKFLAG
     *
     * @mbggenerated
     */
    public Integer getLockflag() {
        return lockflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.LOCKFLAG
     *
     * @param lockflag the value for t_user.LOCKFLAG
     *
     * @mbggenerated
     */
    public void setLockflag(Integer lockflag) {
        this.lockflag = lockflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.LASTNOTICETIME
     *
     * @return the value of t_user.LASTNOTICETIME
     *
     * @mbggenerated
     */
    public Date getLastnoticetime() {
        return lastnoticetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.LASTNOTICETIME
     *
     * @param lastnoticetime the value for t_user.LASTNOTICETIME
     *
     * @mbggenerated
     */
    public void setLastnoticetime(Date lastnoticetime) {
        this.lastnoticetime = lastnoticetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.PUBLICKEY
     *
     * @return the value of t_user.PUBLICKEY
     *
     * @mbggenerated
     */
    public String getPublickey() {
        return publickey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.PUBLICKEY
     *
     * @param publickey the value for t_user.PUBLICKEY
     *
     * @mbggenerated
     */
    public void setPublickey(String publickey) {
        this.publickey = publickey == null ? null : publickey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.DIMISSION
     *
     * @return the value of t_user.DIMISSION
     *
     * @mbggenerated
     */
    public Integer getDimission() {
        return dimission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.DIMISSION
     *
     * @param dimission the value for t_user.DIMISSION
     *
     * @mbggenerated
     */
    public void setDimission(Integer dimission) {
        this.dimission = dimission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.PERMISSION_TYPE
     *
     * @return the value of t_user.PERMISSION_TYPE
     *
     * @mbggenerated
     */
    public String getPermissionType() {
        return permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.PERMISSION_TYPE
     *
     * @param permissionType the value for t_user.PERMISSION_TYPE
     *
     * @mbggenerated
     */
    public void setPermissionType(String permissionType) {
        this.permissionType = permissionType == null ? null : permissionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.LIAISON_OFFICER
     *
     * @return the value of t_user.LIAISON_OFFICER
     *
     * @mbggenerated
     */
    public Boolean getLiaisonOfficer() {
        return liaisonOfficer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.LIAISON_OFFICER
     *
     * @param liaisonOfficer the value for t_user.LIAISON_OFFICER
     *
     * @mbggenerated
     */
    public void setLiaisonOfficer(Boolean liaisonOfficer) {
        this.liaisonOfficer = liaisonOfficer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.TELEPHONE2
     *
     * @return the value of t_user.TELEPHONE2
     *
     * @mbggenerated
     */
    public String getTelephone2() {
        return telephone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.TELEPHONE2
     *
     * @param telephone2 the value for t_user.TELEPHONE2
     *
     * @mbggenerated
     */
    public void setTelephone2(String telephone2) {
        this.telephone2 = telephone2 == null ? null : telephone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.TELEPHONEPUBLIC
     *
     * @return the value of t_user.TELEPHONEPUBLIC
     *
     * @mbggenerated
     */
    public Boolean getTelephonepublic() {
        return telephonepublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.TELEPHONEPUBLIC
     *
     * @param telephonepublic the value for t_user.TELEPHONEPUBLIC
     *
     * @mbggenerated
     */
    public void setTelephonepublic(Boolean telephonepublic) {
        this.telephonepublic = telephonepublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.TELEPHONEPUBLIC2
     *
     * @return the value of t_user.TELEPHONEPUBLIC2
     *
     * @mbggenerated
     */
    public Boolean getTelephonepublic2() {
        return telephonepublic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.TELEPHONEPUBLIC2
     *
     * @param telephonepublic2 the value for t_user.TELEPHONEPUBLIC2
     *
     * @mbggenerated
     */
    public void setTelephonepublic2(Boolean telephonepublic2) {
        this.telephonepublic2 = telephonepublic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.EMAILPUBLIC
     *
     * @return the value of t_user.EMAILPUBLIC
     *
     * @mbggenerated
     */
    public Boolean getEmailpublic() {
        return emailpublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.EMAILPUBLIC
     *
     * @param emailpublic the value for t_user.EMAILPUBLIC
     *
     * @mbggenerated
     */
    public void setEmailpublic(Boolean emailpublic) {
        this.emailpublic = emailpublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.USERINFOPUBLIC
     *
     * @return the value of t_user.USERINFOPUBLIC
     *
     * @mbggenerated
     */
    public Boolean getUserinfopublic() {
        return userinfopublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.USERINFOPUBLIC
     *
     * @param userinfopublic the value for t_user.USERINFOPUBLIC
     *
     * @mbggenerated
     */
    public void setUserinfopublic(Boolean userinfopublic) {
        this.userinfopublic = userinfopublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.NAME_LETTER
     *
     * @return the value of t_user.NAME_LETTER
     *
     * @mbggenerated
     */
    public String getNameLetter() {
        return nameLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.NAME_LETTER
     *
     * @param nameLetter the value for t_user.NAME_LETTER
     *
     * @mbggenerated
     */
    public void setNameLetter(String nameLetter) {
        this.nameLetter = nameLetter == null ? null : nameLetter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.message_target
     *
     * @return the value of t_user.message_target
     *
     * @mbggenerated
     */
    public Integer getMessageTarget() {
        return messageTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.message_target
     *
     * @param messageTarget the value for t_user.message_target
     *
     * @mbggenerated
     */
    public void setMessageTarget(Integer messageTarget) {
        this.messageTarget = messageTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.AVATAR
     *
     * @return the value of t_user.AVATAR
     *
     * @mbggenerated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.AVATAR
     *
     * @param avatar the value for t_user.AVATAR
     *
     * @mbggenerated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.FAVORITE_CONTACTS
     *
     * @return the value of t_user.FAVORITE_CONTACTS
     *
     * @mbggenerated
     */
    public String getFavoriteContacts() {
        return favoriteContacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.FAVORITE_CONTACTS
     *
     * @param favoriteContacts the value for t_user.FAVORITE_CONTACTS
     *
     * @mbggenerated
     */
    public void setFavoriteContacts(String favoriteContacts) {
        this.favoriteContacts = favoriteContacts == null ? null : favoriteContacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.SIGNS
     *
     * @return the value of t_user.SIGNS
     *
     * @mbggenerated
     */
    public String getSigns() {
        return signs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.SIGNS
     *
     * @param signs the value for t_user.SIGNS
     *
     * @mbggenerated
     */
    public void setSigns(String signs) {
        this.signs = signs == null ? null : signs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.COMMONWORKFLOW
     *
     * @return the value of t_user.COMMONWORKFLOW
     *
     * @mbggenerated
     */
    public String getCommonworkflow() {
        return commonworkflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.COMMONWORKFLOW
     *
     * @param commonworkflow the value for t_user.COMMONWORKFLOW
     *
     * @mbggenerated
     */
    public void setCommonworkflow(String commonworkflow) {
        this.commonworkflow = commonworkflow == null ? null : commonworkflow.trim();
    }
}
